
services:
  app:
    build: .
    container_name: youtube-app
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    environment:
      # Pass-through secrets from host .env or environment
      - SEO_YOUTUBE_API_KEY=${SEO_YOUTUBE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Make app use docker network host for Ollama
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_TIMEOUT=600
      - OLLAMA_NUM_PREDICT=200
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}

    ports:
      - "8000:8000"   # Web monitor
    volumes:
      - ./:/app
    command: ["python", "start_services.py", "--config", "config/video.docker.yaml", "--sources", "config/sources.yaml", "--log-level", "INFO", "--monitor-host", "0.0.0.0", "--monitor-port", "8000"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped

  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: youtube-ci
    working_dir: /app
    volumes:
      - ./:/app
    # Default: run full local CI (lint + unit + integration)
    command: ["bash", "-lc", "bash /app/scripts/ci.sh all"]


volumes:
  ollama:
