video_path: ./test_video.mp4
thumbnail_path: ./thumbnail.jpg
title: '"Automatisez votre YouTube : Créez des playlists en auto !"'
description: 'L''automatisation du contenu de votre canal YouTube peut être un outil
  puissant pour augmenter la visibilité et l''engagement de vos abonnés. En créant
  des playlists auto-générées, vous pouvez automatiser le processus de publication
  de vidéos en fonction d''un calendrier prédefini. Cela permet de réduire les délais
  de publication et de maximiser l''efficacité de votre stratégie de contenu.


  Les playlists auto-générées peuvent également aider à personnaliser l''expérience
  de vos abonnés. En fonction des préférences et des intérêts de chaque abonné, vous
  pouvez créer des playlists qui leur sont adaptées. Cela peut être réalisé grâce
  à l''utilisation d''applications tierces telles que TubeBuddy ou VidIQ, qui proposent
  des fonctionnalités d''analyse et de personnalisation avancées pour les créateurs'
tags:
- automatisation youtube
- planification auto
- playlist
- gestion de contenus
- intégration
- api youtube
- scripting python
- google apps script
- youtube api
- programmation automatique
- gestion de calendrier
- synchronisation
- importation
- exportation
- gestion des fichiers
audio_language: fr
category_id: 22
privacy_status: private
enhance:
  enabled: true
  quality: youtube
  codec: h264
  hwaccel: none
  scale: null
  fps: 30
  denoise: false
  sharpen: true
  deband: true
  deblock: false
  sharpen_amount: 1.0
  contrast: 1.08
  saturation: 1.12
  deinterlace: false
  color_fix: false
  loudnorm: false
  crf: 16
  bitrate: null
  preset: slow
  reencode_audio: true
  audio_bitrate: 192k
seo:
  provider: openai
  force_title_from_description: true
subtitles:
  enabled: false
  whisper_model: base
  languages:
  - fr
  auto_detect: true
  translate_to_english: false
  upload_to_youtube: true
  draft_mode: false
  replace_existing: false
vision:
  enabled: false
seo_advanced:
  enabled: true
  trends:
    enabled: true
    region: FR
    update_interval: 3600
    cache_duration: 1800
  competitor_analysis:
    enabled: true
    max_competitors: 20
    min_views_threshold: 1000
  ab_testing:
    enabled: true
    storage_path: ./ab_tests
    auto_generate_variants: true
    max_variants: 4
multi_accounts:
  enabled: false
  config_path: config/multi_accounts.json
  load_balancing:
    strategy: quota_based
    auto_switch: true
    fallback_enabled: true
  default_limits:
    daily_quota_limit: 10000
    daily_upload_limit: 6
    api_calls_per_upload: 1600
notifications:
  email:
    enabled: true
    host: smtp.gmail.com
    port: 587
    tls: true
    username: "ahmedabladon33@gmail.com"
    password_env: EMAIL_PASSWORD
    from: "ahmedabladon33@gmail.com"
    to:
      - "ahmedabladon33@gmail.com"
