name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
          pip install flake8

      - name: Lint (flake8)
        run: |
          flake8 src/ tests/ --max-line-length=160 --extend-ignore=E203,W503

      - name: Run tests
        run: |
          pytest -v --cov=src --cov-report=xml --junitxml=test-results.xml

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-results.xml
            coverage.xml

  deploy:
    # Déploiement simple uniquement sur push vers main, après succès des tests
    needs: tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy (conditional on secrets presence)
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: production
        run: |
          set -e
          echo "Starting deploy to $ENVIRONMENT"
          if [ -z "$GOOGLE_CREDENTIALS" ] || [ -z "$YOUTUBE_CREDENTIALS" ]; then
            echo "Secrets missing (GOOGLE_CREDENTIALS/YOUTUBE_CREDENTIALS). Skipping deploy safely."
            exit 0
          fi
          mkdir -p config
          echo "$GOOGLE_CREDENTIALS" > config/google_credentials.json
          echo "$YOUTUBE_CREDENTIALS" > config/youtube_credentials.json
          echo "Credentials written to config/"
          # Placez ici vos commandes effectives de déploiement, par ex.:
          # ./deploy.sh
          echo "(placeholder) Deployment actions executed"
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"🚀 Déploiement terminé sur '$ENVIRONMENT'"}' \
              "$SLACK_WEBHOOK_URL" || true
          fi
